import connectDB from "@/lib/db";
import Product from "@/model/product";

export async function GET() {
  try {
    await connectDB();

    await Product.deleteMany({});

    await Product.insertMany([
  {
    title: "Denim Shirt",
    description: "A comfortable denim shirt",
    image: "https://picsum.photos/500/300?random=" + Math.floor(Math.random() * 1000),
    price: Number((29.99 * 99).toFixed(2)),
    category: "Shirts",
  },
  {
    title: "Leather Jacket",
    description: "A stylish leather jacket",
    image: "https://picsum.photos/500/300?random=" + Math.floor(Math.random() * 1000),
    price: Number((99.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Running Shoes",
    description: "Comfortable running shoes for daily wear",
    image: "https://picsum.photos/500/300",
    price: Number((49.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Casual T-Shirt",
    description: "Soft cotton casual t-shirt",
    image: "https://picsum.photos/500/300",
    price: Number((19.99 * 99).toFixed(2)),
    category: "T-Shirts",
  },
  {
    title: "Slim Fit Jeans",
    description: "Modern slim fit blue jeans",
    image: "https://picsum.photos/500/300",
    price: Number((39.99 * 99).toFixed(2)),
    category: "Jeans",
  },
  {
    title: "Formal Shirt",
    description: "Perfect formal shirt for office wear",
    image: "https://picsum.photos/500/300",
    price: Number((34.99 * 99).toFixed(2)),
    category: "Shirts",
  },
  {
    title: "Hoodie",
    description: "Warm fleece hoodie",
    image: "https://picsum.photos/500/300",
    price: Number((44.99 * 99).toFixed(2)),
    category: "Hoodies",
  },
  {
    title: "Sneakers",
    description: "Stylish sneakers for everyday use",
    image: "https://picsum.photos/500/300",
    price: Number((59.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Cargo Pants",
    description: "Durable cargo pants with pockets",
    image: "https://picsum.photos/500/300",
    price: Number((45.99 * 99).toFixed(2)),
    category: "Pants",
  },
  {
    title: "Polo T-Shirt",
    description: "Classic polo t-shirt",
    image: "https://picsum.photos/500/300",
    price: Number((24.99 * 99).toFixed(2)),
    category: "T-Shirts",
  },
  {
    title: "Winter Coat",
    description: "Heavy winter coat for cold weather",
    image: "https://picsum.photos/500/300",
    price: Number((129.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Sports Shorts",
    description: "Breathable sports shorts",
    image: "https://picsum.photos/500/300",
    price: Number((22.99 * 99).toFixed(2)),
    category: "Shorts",
  },
  {
    title: "Flip Flops",
    description: "Comfortable beach flip flops",
    image: "https://picsum.photos/500/300",
    price: Number((14.99 * 99).toFixed(2)),
    category: "Footwear",
  },
  {
    title: "Track Pants",
    description: "Flexible track pants for workouts",
    image: "https://picsum.photos/500/300",
    price: Number((32.99 * 99).toFixed(2)),
    category: "Pants",
  },
  {
    title: "Graphic Tee",
    description: "Printed graphic t-shirt",
    image: "https://picsum.photos/500/300",
    price: Number((21.99 * 99).toFixed(2)),
    category: "T-Shirts",
  },
  {
    title: "Bomber Jacket",
    description: "Classic bomber jacket style",
    image: "https://picsum.photos/500/300",
    price: Number((89.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Canvas Shoes",
    description: "Lightweight canvas shoes",
    image: "https://picsum.photos/500/300",
    price: Number((36.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Chinos",
    description: "Elegant chino pants",
    image: "https://picsum.photos/500/300",
    price: Number((41.99 * 99).toFixed(2)),
    category: "Pants",
  },
  {
    title: "Tank Top",
    description: "Sleeveless gym tank top",
    image: "https://picsum.photos/500/300",
    price: Number((17.99 * 99).toFixed(2)),
    category: "Gym Wear",
  },
  {
    title: "Wool Sweater",
    description: "Warm wool sweater",
    image: "https://picsum.photos/500/300",
    price: Number((54.99 * 99).toFixed(2)),
    category: "Sweaters",
  },
  {
    title: "Sports Cap",
    description: "Adjustable sports cap",
    image: "https://picsum.photos/500/300",
    price: Number((12.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Leather Boots",
    description: "Premium leather boots",
    image: "https://picsum.photos/500/300",
    price: Number((119.99 * 99).toFixed(2)),
    category: "Footwear",
  },
  {
    title: "Zip Hoodie",
    description: "Casual zip-up hoodie",
    image: "https://picsum.photos/500/300",
    price: Number((47.99 * 99).toFixed(2)),
    category: "Hoodies",
  },
  {
    title: "Printed Shirt",
    description: "Trendy printed shirt",
    image: "https://picsum.photos/500/300",
    price: Number((27.99 * 99).toFixed(2)),
    category: "Shirts",
  },
  {
    title: "Training Shoes",
    description: "Perfect training shoes for gym",
    image: "https://picsum.photos/500/300",
    price: Number((64.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Beanie",
    description: "Winter wool beanie",
    image: "https://picsum.photos/500/300",
    price: Number((11.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Joggers",
    description: "Comfortable jogger pants",
    image: "https://picsum.photos/500/300",
    price: Number((38.99 * 99).toFixed(2)),
    category: "Pants",
  },
  {
    title: "Rain Jacket",
    description: "Waterproof rain jacket",
    image: "https://picsum.photos/500/300",
    price: Number((74.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Loafers",
    description: "Elegant casual loafers",
    image: "https://picsum.photos/500/300",
    price: Number((58.99 * 99).toFixed(2)),
    category: "Footwear",
  },
  {
    title: "Cotton Shorts",
    description: "Soft cotton shorts",
    image: "https://picsum.photos/500/300",
    price: Number((20.99 * 99).toFixed(2)),
    category: "Shorts",
  },
  {
    title: "Gym Gloves",
    description: "Durable gym workout gloves",
    image: "https://picsum.photos/500/300",
    price: Number((15.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "V-Neck T-Shirt",
    description: "Stylish v-neck t-shirt",
    image: "https://picsum.photos/500/300",
    price: Number((18.99 * 99).toFixed(2)),
    category: "T-Shirts",
  },
  {
    title: "Formal Pants",
    description: "Elegant formal trousers",
    image: "https://picsum.photos/500/300",
    price: Number((43.99 * 99).toFixed(2)),
    category: "Pants",
  },
  {
    title: "Puffer Jacket",
    description: "Warm puffer winter jacket",
    image: "https://picsum.photos/500/300",
    price: Number((109.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Slip-On Shoes",
    description: "Easy slip-on shoes",
    image: "https://picsum.photos/500/300",
    price: Number((34.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Casual Blazer",
    description: "Modern casual blazer",
    image: "https://picsum.photos/500/300",
    price: Number((94.99 * 99).toFixed(2)),
    category: "Blazers",
  },
  {
    title: "Sports Jacket",
    description: "Light sports jacket",
    image: "https://picsum.photos/500/300",
    price: Number((79.99 * 99).toFixed(2)),
    category: "Jackets",
  },
  {
    title: "Sleeveless Hoodie",
    description: "Gym sleeveless hoodie",
    image: "https://picsum.photos/500/300",
    price: Number((29.99 * 99).toFixed(2)),
    category: "Gym Wear",
  },
  {
    title: "Ankle Boots",
    description: "Stylish ankle boots",
    image: "https://picsum.photos/500/300",
    price: Number((89.99 * 99).toFixed(2)),
    category: "Footwear",
  },
  {
    title: "Check Shirt",
    description: "Classic checkered shirt",
    image: "https://picsum.photos/500/300",
    price: Number((31.99 * 99).toFixed(2)),
    category: "Shirts",
  },
  {
    title: "Sports Socks",
    description: "Comfortable ankle socks",
    image: "https://picsum.photos/500/300",
    price: Number((9.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Casual Sandals",
    description: "Lightweight casual sandals",
    image: "https://picsum.photos/500/300",
    price: Number((25.99 * 99).toFixed(2)),
    category: "Footwear",
  },
  {
    title: "Wrist Watch",
    description: "Elegant wrist watch",
    image: "https://picsum.photos/500/300",
    price: Number((149.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Laptop Bag",
    description: "Spacious laptop backpack",
    image: "https://picsum.photos/500/300",
    price: Number((69.99 * 99).toFixed(2)),
    category: "Bags",
  },
  {
    title: "Travel Backpack",
    description: "Durable travel backpack",
    image: "https://picsum.photos/500/300",
    price: Number((79.99 * 99).toFixed(2)),
    category: "Bags",
  },
  {
    title: "Wallet",
    description: "Premium leather wallet",
    image: "https://picsum.photos/500/300",
    price: Number((26.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Sports Bottle",
    description: "Reusable water bottle",
    image: "https://picsum.photos/500/300",
    price: Number((13.99 * 99).toFixed(2)),
    category: "Gym Wear",
  },
  {
    title: "Compression Tights",
    description: "Stretchable gym tights",
    image: "https://picsum.photos/500/300",
    price: Number((35.99 * 99).toFixed(2)),
    category: "Gym Wear",
  },
  {
    title: "Sunglasses",
    description: "UV protection sunglasses",
    image: "https://picsum.photos/500/300",
    price: Number((24.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Duffel Bag",
    description: "Large gym duffel bag",
    image: "https://picsum.photos/500/300",
    price: Number((55.99 * 99).toFixed(2)),
    category: "Bags",
  },
  {
    title: "Formal Shoes",
    description: "Classic formal shoes",
    image: "https://picsum.photos/500/300",
    price: Number((84.99 * 99).toFixed(2)),
    category: "Shoes",
  },
  {
    title: "Sweatshirt",
    description: "Soft warm sweatshirt",
    image: "https://picsum.photos/500/300",
    price: Number((42.99 * 99).toFixed(2)),
    category: "Sweaters",
  },
  {
    title: "Cardigan",
    description: "Comfortable wool cardigan",
    image: "https://picsum.photos/500/300",
    price: Number((57.99 * 99).toFixed(2)),
    category: "Sweaters",
  },
  {
    title: "Fitness Band",
    description: "Track your daily fitness",
    image: "https://picsum.photos/500/300",
    price: Number((89.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Bluetooth Earbuds",
    description: "Wireless music earbuds",
    image: "https://picsum.photos/500/300",
    price: Number((69.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Smart Watch",
    description: "Advanced smart watch",
    image: "https://picsum.photos/500/300",
    price: Number((199.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Phone Cover",
    description: "Protective phone case",
    image: "https://picsum.photos/500/300",
    price: Number((16.99 * 99).toFixed(2)),
    category: "Accessories",
  },
  {
    title: "Gaming Mouse",
    description: "High precision gaming mouse",
    image: "https://picsum.photos/500/300",
    price: Number((49.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Mechanical Keyboard",
    description: "RGB mechanical keyboard",
    image: "https://picsum.photos/500/300",
    price: Number((89.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Portable Speaker",
    description: "Wireless portable speaker",
    image: "https://picsum.photos/500/300",
    price: Number((59.99 * 99).toFixed(2)),
    category: "Electronics",
  },
  {
    title: "Gaming Headset",
    description: "Surround sound gaming headset",
    image: "https://picsum.photos/500/300",
    price: Number((79.99 * 99).toFixed(2)),
    category: "Electronics",
  }
]);

    return Response.json({
      message: "Products seeded successfully",
    });
  } catch (error) {
    console.log(error);

    return Response.json({
      error: error.message,
    });
  }
}
